(()=>{const P=LogicParser,$=s=>document.querySelector(s),body=$('#proof');let premises=[],goal=null,activeInput=null;
function refs(s){if(!s.trim())return[];return s.split(',').map(x=>{x=x.trim();let m=x.match(/^(\d+)\s*-\s*(\d+)$/);return m?{type:'range',start:+m[1],end:+m[2]}:{type:'line',n:+x}}).filter(x=>x.type==='range'||Number.isInteger(x.n))}
function addRow(formula='',ref='',rule=''){let n=body.children.length+1,tr=document.createElement('tr');tr.innerHTML=`<td>${n}</td><td><input class="formula" value="${formula.replace(/"/g,'&quot;')}"></td><td><input class="refs" value="${ref}" placeholder="1,2 또는 2-4"></td><td><select class="rule"><option value="">선택</option><option>Premise</option><option>AS</option><option>R</option><option>∧I</option><option>∧E</option><option>∨I</option><option>→E</option><option>→I</option><option>⊥I</option><option>¬I</option></select></td><td class="status muted">미검증</td>`;body.appendChild(tr);if(rule)tr.querySelector('.rule').value=rule}
function renum(){[...body.children].forEach((r,i)=>r.children[0].textContent=i+1)}
function rows(){let open=[];return[...body.children].map((tr,i)=>{let rule=tr.querySelector('.rule').value,parsed=refs(tr.querySelector('.refs').value),range=parsed.find(x=>x.type==='range');if((rule==='→I'||rule==='¬I')&&range&&open.at(-1)===range.start)open.pop();if(rule==='AS')open.push(i+1);let r={n:i+1,formula:tr.querySelector('.formula').value.trim(),refs:parsed,rule,status:tr.querySelector('.status'),scope:[...open]};tr.dataset.depth=r.scope.length;return r})}
function load(){try{premises=$('#premises').value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(P.parse);goal=P.parse($('#conclusion').value);$('#problem').innerHTML=`<b>${premises.map(P.show).join(', ')}</b> &there4; <b>${P.show(goal)}</b>`;body.innerHTML='';premises.forEach(x=>addRow(P.show(x),'','Premise'));addRow();$('#summary').textContent='문제를 불러왔습니다. 증명을 계속하세요.'}catch(e){$('#problem').innerHTML=`<span class="bad">입력 오류: ${e.message}</span>`}}
function check(){let rs=rows(),asts=rs.map(r=>{try{return P.parse(r.formula)}catch{return null}}),all=true;rs.forEach((r,i)=>{let[ok,msg]=LogicRules.validate(i,rs,asts,premises);r.status.className='status '+(ok?'ok':'bad');r.status.textContent=(ok?'✓ ':'✗ ')+msg;if(!ok)all=false});let reaches=asts.length&&goal&&P.eq(asts.at(-1),goal),open=rs.length?rs.at(-1).scope.length:0;if(open){all=false;$('#summary').innerHTML='<span class="bad">닫히지 않은 보조증명이 있습니다. →I 또는 ¬I로 가정을 해제하세요.</span>';return}$('#summary').innerHTML=all&&reaches?'<span class="ok">✓ 증명이 완성되었습니다. 모든 행이 올바르고 목표 결론에 도달했습니다.</span>':all?'<span class="bad">각 행은 올바르지만 아직 목표 결론에 도달하지 않았습니다.</span>':'<span class="bad">수정이 필요한 행이 있습니다. 각 행의 피드백을 확인하세요.</span>'}
function isFormulaInput(x){return x&&(x.classList?.contains('formula')||x.id==='conclusion'||x.id==='premises')}
document.addEventListener('focusin',e=>{if(isFormulaInput(e.target))activeInput=e.target});
document.addEventListener('input',e=>{if(isFormulaInput(e.target)&&e.target.value.includes('~')){let p=e.target.selectionStart;e.target.value=e.target.value.replace(/~/g,'¬');e.target.selectionStart=e.target.selectionEnd=p}});
document.querySelectorAll('.symbols button').forEach(b=>b.onclick=()=>{let x=activeInput||$('#conclusion');let s=x.selectionStart??x.value.length,e=x.selectionEnd??s;x.value=x.value.slice(0,s)+b.textContent+x.value.slice(e);x.focus();x.selectionStart=x.selectionEnd=s+b.textContent.length});$('#load').onclick=load;$('#add').onclick=()=>addRow();$('#remove').onclick=()=>{if(body.lastElementChild){body.lastElementChild.remove();renum()}};$('#check').onclick=check;load()})();
