(()=>{const P=LogicParser,$=s=>document.querySelector(s),body=$('#proof');let premises=[],goal=null,activeInput=null;
function refs(s){if(!s.trim())return[];return s.split(',').map(x=>{x=x.trim();let m=x.match(/^(\d+)\s*-\s*(\d+)$/);return m?{type:'range',start:+m[1],end:+m[2]}:{type:'line',n:+x}}).filter(x=>x.type==='range'||Number.isInteger(x.n))}
function addRow(formula='',ref='',rule=''){let n=body.children.length+1,tr=document.createElement('tr');tr.className='proof-row';tr.innerHTML=`<td>${n}</td><td><input class="formula" value="${formula.replace(/"/g,'&quot;')}"></td><td><input class="refs" value="${ref}" placeholder="1,2 또는 2-4"></td><td><select class="rule"><option value="">선택</option><option>Premise</option><option>AS</option><option>R</option><option>∧I</option><option>∧E</option><option>∨I</option><option>∨E</option><option>→E</option><option>→I</option><option>⊥I</option><option>⊥E</option><option>¬I</option><option>↔I</option><option>↔E</option></select></td><td class="status muted">미검증</td>`;body.appendChild(tr);if(rule)tr.querySelector('.rule').value=rule}
function renum(){[...body.children].forEach((r,i)=>r.children[0].textContent=i+1)}
function proofState(){const raw=[...body.children].map((tr,i)=>({n:i+1,formula:tr.querySelector('.formula').value.trim(),refs:refs(tr.querySelector('.refs').value),rule:tr.querySelector('.rule').value,status:tr.querySelector('.status'),tr}));const engine=LogicProofEngine.analyze(raw);engine.rows.forEach(r=>{r.tr.dataset.depth=r.scope.length;r.tr.dataset.closes=r.closes?'true':'false';r.tr.style.setProperty('--depth',r.scope.length)});return engine}
function load(){try{premises=$('#premises').value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(P.parse);goal=P.parse($('#conclusion').value);$('#problem').innerHTML=`<b>${premises.map(P.show).join(', ')}</b> &there4; <b>${P.show(goal)}</b>`;body.innerHTML='';premises.forEach(x=>addRow(P.show(x),'','Premise'));addRow();$('#summary').textContent='문제를 불러왔습니다. 증명을 계속하세요.'}catch(e){$('#problem').innerHTML=`<span class="bad">입력 오류: ${e.message}</span>`}}
function check(){const engine=proofState(),rs=engine.rows,asts=rs.map(r=>{try{return P.parse(r.formula)}catch{return null}});let all=true;rs.forEach((r,i)=>{const[ok,msg]=LogicRules.validate(i,rs,asts,premises,engine);r.status.className='status '+(ok?'ok':'bad');r.status.textContent=(ok?'✓ ':'✗ ')+msg;if(!ok)all=false});if(engine.openScopes.length){all=false;$('#summary').innerHTML=`<span class="bad">닫히지 않은 보조증명이 있습니다. 마지막 문장 끝에 /를 입력해 닫으세요. 열린 AS 행: ${engine.openScopes.join(', ')}</span>`;return}const reaches=asts.length&&goal&&P.eq(asts.at(-1),goal);$('#summary').innerHTML=all&&reaches?'<span class="ok">✓ 증명이 완성되었습니다. 모든 행이 올바르고 목표 결론에 도달했습니다.</span>':all?'<span class="bad">각 행은 올바르지만 아직 목표 결론에 도달하지 않았습니다.</span>':'<span class="bad">수정이 필요한 행이 있습니다. 각 행의 피드백을 확인하세요.</span>'}
function isFormulaInput(x){return x&&(x.classList?.contains('formula')||x.id==='conclusion'||x.id==='premises')}
document.addEventListener('focusin',e=>{if(isFormulaInput(e.target))activeInput=e.target});document.addEventListener('input',e=>{if(isFormulaInput(e.target)&&e.target.value.includes('~')){let p=e.target.selectionStart;e.target.value=e.target.value.replace(/~/g,'¬');e.target.selectionStart=e.target.selectionEnd=p}});document.querySelectorAll('.symbols button').forEach(b=>b.onclick=()=>{let x=activeInput||$('#conclusion'),s=x.selectionStart??x.value.length,e=x.selectionEnd??s;x.value=x.value.slice(0,s)+b.textContent+x.value.slice(e);x.focus();x.selectionStart=x.selectionEnd=s+b.textContent.length});$('#load').onclick=load;$('#add').onclick=()=>addRow();$('#remove').onclick=()=>{if(body.lastElementChild){body.lastElementChild.remove();renum()}};$('#check').onclick=check;load()})();
